### PR TITLE
fix: selectively filter files when recursing

### LINKED ISSUE #1101: bug: --only-files breaks --recurse
# System context

- eza v0.19.0 \[+git\]
- Invoking `eza --recurse --only-files`
- zsh 5.9 (x86_64-apple-darwin23.0) running in iTerm2 3.5.2
- macOS 14.6.1 (Sonoma) running on a 2021 MacBook Pro (M1)

# Observed behaviour

eza enumerates only files in the target directory.

# Expected behaviour

eza recursively enumerates files contained in the target directory and its subdirectories.

# Notes

While I can appreciate that `--only-files` says "don't look at directories", this behaviour leaves eza with no way to recursively enumerate files in a directory tree without also enumerating the directories themselves. Specifying `--recurse` should modify the behaviour of `--only-files` to match the UX expectation here.

### PR DESCRIPTION
**Pull request by PThorpe92**
fixes #1101 

eza

### CODE REVIEW

File: src/fs/filter.rs [hunk 1]
```diff
@@ -85,38 +85,28 @@ pub struct FileFilter {
 impl FileFilter {
     /// Remove every file in the given vector that does *not* pass the
     /// filter predicate for files found inside a directory.
-    pub fn filter_child_files(&self, files: &mut Vec<File<'_>>) {
+#[rustfmt::skip]
+    pub fn filter_child_files(&self, is_recurse: bool, files: &mut Vec<File<'_>>) {
```
Comment (cafkafk) [inline src/fs/filter.rs:89]:
```suggestion
    #[rustfmt::skip]
    pub fn filter_child_files(&self, is_recurse: bool, files: &mut Vec<File<'_>>) {
```

**Review by cafkafk — CHANGES_REQUESTED** [review]

**Review by cafkafk — APPROVED** [review]
Nice, LGTM, glad to see this fixed!
